# Generated by Django 3.2.8 on 2021-10-25 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Port',
            new_name='Post',
        ),
    ]
